united-build: 
language: generic
sudo: required
services:
- docker
# DISABLE before_install if you want build with shotcut
before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull davidva/unibuild-24
script:
# ENABLE tne next line and delete add a "#" the next lines; if you want build with shotcut
#- travis_wait 40 docker run --cap-add=SYS_ADMIN davidva/unibuild /bin/sh /urpms -g UnitedRPMs/kodi-platform -s kodi-platform.spec -t fedora-24-x86_64
- "docker run -v $(pwd):/root/enjoy --cap-add=SYS_ADMIN davidva/unibuild-24 /bin/sh /urpms -g UnitedRPMs/chrome-gnome-shell -s chrome-gnome-shell.spec -r true -d 'dist .fc24' -c true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bbc656ea277114ba4fd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

